version: '3.7'
services:
  postgres:
    # based on postgis/postgis with gdal-bin
    build:
        context: ./db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes:
      - ./db:/data
  web:
    image: node:16
    command: "npm start"
    volumes:
      - ./web:/app
    working_dir: /app
    environment:
      - PORT=4000
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.template:/etc/nginx/templates/default.conf.template
      - ../:/var/www
    ports:
      - 8088:80
    environment:
        - NGINX_PORT=80
        - APP_PORT=4000
        - APP_NAME=web
