version: '3.7'
services:
  postgres:
    #image: postgis/postgis with gdal-bin
    build:
        context: .
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes:
      - ./:/data
